---
apiVersion: v1
kind: Service
metadata:
  name: sample-service
  namespace: prod-ns
  labels:
    app: sample
spec:
  ports:
    - name: sample
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: sample
  type: ClusterIP